<Workspace Version="1.3.3.4111" X="-663.202687050871" Y="1041.49890392107" zoom="0.685157988156056" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.Categories guid="f4486a59-2772-4746-8a06-1cf74eba0b7e" type="DSRevitNodesUI.Categories" nickname="Categories" x="767.745924932925" y="-566.856860282806" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="425:Rooms" />
    <DSRevitNodesUI.ElementsOfCategory guid="c9db86df-911c-4ec6-8b9a-3d04f8022379" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="1025.99049430826" y="-725.807486176204" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <CoreNodeModels.Watch guid="a4032ef5-e977-4640-8d1c-b19a4b917b2f" type="CoreNodeModels.Watch" nickname="Watch" x="1762.28165933791" y="-281.757496259667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="6867334b-7f3d-4776-b39c-2ecbcdd46dfe" type="CoreNodeModels.Watch" nickname="Watch" x="2778.43631174816" y="-714.892733765128" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="98ecec0f-dde9-4f01-a361-8585ba0f082c" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.CenterBoundary" x="1249.35097224692" y="-567.233789037341" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Room.CenterBoundary">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9902f956-a609-4d03-8111-059c622951b4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.Location" x="1602.45444740085" y="-785.541230271985" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Room.Location">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="74a5a6f2-30ae-4f8c-a6f2-f00092b37c17" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="PolyCurve.ByJoinedCurves" x="1451.71638311381" y="-639.685602804499" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.ByJoinedCurves@Autodesk.DesignScript.Geometry.Curve[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d9184b22-6b44-4dd6-be37-3a11248140bb" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Curve.ExtrudeAsSolid" x="1524.16819688097" y="-391.100931430975" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid@double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d1d74e00-df06-4f2f-a799-104b79048f85" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Centroid" x="1730.2811153565" y="-497.280313675947" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Centroid">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="86c7ac88-86e1-454e-a58e-616225318074" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.X" x="1943.88904904933" y="-674.662340485196" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.X">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0be9264f-f4de-48c7-a0f4-c51c405d535e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Y" x="1992.42178339003" y="-541.001235776819" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Y">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7abb9cba-f9d5-452f-9f8e-f1e310e2f1d8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Z" x="1953.88240267239" y="-396.097608242503" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Z">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="c547d0b5-0bc7-47ab-8fc6-e378856778e3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ByTwoPoints" x="2212.12321814464" y="-621.347272464429" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="7801f1ec-b31a-4f3c-950a-18b02fb45b2b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.MoveByVector" x="2414.80473133982" y="-727.038205948684" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.MoveByVector@Autodesk.DesignScript.Geometry.Vector">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Categories guid="a6e8b99a-eb32-4899-9f2e-4dd1115dc75a" type="DSRevitNodesUI.Categories" nickname="Categories" x="776.810021476078" y="-991.421920141332" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="424:RoomTags" />
    <DSRevitNodesUI.ElementsOfCategory guid="d9eb3aeb-1001-4aec-b56e-6299ed4d917f" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="1065.35897076479" y="-1062.32879780165" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="99903871-f41b-4932-b744-c6aeb5170bb4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ByTwoPoints" x="2160.5240874529" y="-785.914704110045" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Watch guid="71242c0d-d942-4e38-b0ee-9b459b7f8995" type="CoreNodeModels.Watch" nickname="Watch" x="1387.73171027734" y="-1213.36574999088" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <CoreNodeModels.Watch guid="b0bebbdc-e0e2-43d2-a79d-fd1f284960c9" type="CoreNodeModels.Watch" nickname="Watch" x="2157.6012822545" y="-1227.1931098701" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="87fae961-b6c7-43a2-aa04-ac731fa1316b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1215" y="-1768" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="4af1bf8b-d828-4a03-9903-984907b9fe54" type="PythonNodeModels.PythonNode" nickname="Room Tag MOVE" x="1699.08956440265" y="-1255.41381432885" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

import clr
clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)

doc = DocumentManager.Instance.CurrentDBDocument
 
#The inputs to this node will be stored as a list in the IN variables.
rtags = UnwrapElement(IN[0])

TransactionManager.Instance.EnsureInTransaction(doc)
	
for rt in rtags:
	if rt.Room != None:
		rt.Location.Move(rt.Room.Location.Point - rt.Location.Point)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

#Assign your output to the OUT variable.
OUT = rtags</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="f4486a59-2772-4746-8a06-1cf74eba0b7e" start_index="0" end="c9db86df-911c-4ec6-8b9a-3d04f8022379" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9db86df-911c-4ec6-8b9a-3d04f8022379" start_index="0" end="98ecec0f-dde9-4f01-a361-8585ba0f082c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9db86df-911c-4ec6-8b9a-3d04f8022379" start_index="0" end="9902f956-a609-4d03-8111-059c622951b4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9db86df-911c-4ec6-8b9a-3d04f8022379" start_index="0" end="7801f1ec-b31a-4f3c-950a-18b02fb45b2b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="98ecec0f-dde9-4f01-a361-8585ba0f082c" start_index="0" end="74a5a6f2-30ae-4f8c-a6f2-f00092b37c17" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9902f956-a609-4d03-8111-059c622951b4" start_index="0" end="c547d0b5-0bc7-47ab-8fc6-e378856778e3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9902f956-a609-4d03-8111-059c622951b4" start_index="0" end="99903871-f41b-4932-b744-c6aeb5170bb4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="74a5a6f2-30ae-4f8c-a6f2-f00092b37c17" start_index="0" end="d9184b22-6b44-4dd6-be37-3a11248140bb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9184b22-6b44-4dd6-be37-3a11248140bb" start_index="0" end="d1d74e00-df06-4f2f-a799-104b79048f85" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9184b22-6b44-4dd6-be37-3a11248140bb" start_index="0" end="a4032ef5-e977-4640-8d1c-b19a4b917b2f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1d74e00-df06-4f2f-a799-104b79048f85" start_index="0" end="86c7ac88-86e1-454e-a58e-616225318074" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1d74e00-df06-4f2f-a799-104b79048f85" start_index="0" end="0be9264f-f4de-48c7-a0f4-c51c405d535e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1d74e00-df06-4f2f-a799-104b79048f85" start_index="0" end="7abb9cba-f9d5-452f-9f8e-f1e310e2f1d8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1d74e00-df06-4f2f-a799-104b79048f85" start_index="0" end="c547d0b5-0bc7-47ab-8fc6-e378856778e3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1d74e00-df06-4f2f-a799-104b79048f85" start_index="0" end="99903871-f41b-4932-b744-c6aeb5170bb4" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c547d0b5-0bc7-47ab-8fc6-e378856778e3" start_index="0" end="7801f1ec-b31a-4f3c-950a-18b02fb45b2b" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7801f1ec-b31a-4f3c-950a-18b02fb45b2b" start_index="0" end="6867334b-7f3d-4776-b39c-2ecbcdd46dfe" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a6e8b99a-eb32-4899-9f2e-4dd1115dc75a" start_index="0" end="d9eb3aeb-1001-4aec-b56e-6299ed4d917f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9eb3aeb-1001-4aec-b56e-6299ed4d917f" start_index="0" end="71242c0d-d942-4e38-b0ee-9b459b7f8995" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d9eb3aeb-1001-4aec-b56e-6299ed4d917f" start_index="0" end="4af1bf8b-d828-4a03-9903-984907b9fe54" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-5300.27916939101" eyeY="6085.9288101278" eyeZ="10414.4171999411" lookX="6318.71025014854" lookY="-4414.52193145996" lookZ="-8927.74663504077" upX="0.0963433351683431" upY="0.985996037070489" upZ="-0.136124122219018" />
  </Cameras>
</Workspace>